pipeline:
  identifier: Build_BuildOn_1695291316783
  name: Build BuildOn
  orgIdentifier: default
  projectIdentifier: buildon
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1695291009490
        repoName: deenaboopathy/BuildOn
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: GitClone
                  name: GitClone_1
                  identifier: GitClone_1
                  spec:
                    connectorRef: account.Github_OAuth_1695291009490
                    repoName: BuildOn
                    build:
                      type: branch
                      spec:
                        branch: master
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    connectorRef: account.harnessImage
                    image: maven:latest
                    shell: Sh
                    command: |-
                      cd webapp
                      mvn clean package -Dskiptests
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
